### PR TITLE
Added tests and Python3 compatibility

### PR DESCRIPTION
**Pull request by eoinwoods**
Hi Danny,

Thanks for writing this really cool module.  I've enjoyed using it.  On my fork, I've added some unit tests, made it work for Python3 and added GripsOpen and GripsClose (as synonyms for OpenGrips and CloseGrips) for consistency with the other verb names.

Merge in if you like it, otherwise, feel free to bounce it.

Cheers,

Eoin.

### CODE REVIEW

**Comment by dannystaple** [comment]
Awesome. I will merge it. I am thinking of writing a compatible api for the
u factory u arm, with a shim on the arduino - not worked out the detail yet
as the u arm has servos, and position feedback.

**Comment by eoinwoods** [comment]
Brilliant, thanks.  I have a few other ideas for bits and pieces with it, so I’ll send pull requests when I get around to those.

An arm with position feedback would be cool - which kit is that?  I’d be interested in getting it.

Oh, BTW, just for laughs I added you to the Gitter feed for my fork.  Gitter is persistent chat for Github - it’s quite nice when you’re cooperating on something.  Just added you in case you’re interested in trying it.

Cheers,

E.

> On 7 Jan 2015, at 07:44, Danny Staple <notifications@github.com> wrote:
> 
> Awesome. I will merge it. I am thinking of writing a compatible api for the 
> u factory u arm, with a shim on the arduino - not worked out the detail yet 
> as the u arm has servos, and position feedback. 
> 
> On Tue, 6 Jan 2015 21:32 Eoin Woods <notifications@github.com> wrote: 
> 
> > Hi Danny, 
> > 
> > Thanks for writing this really cool module. I've enjoyed using it. On my 
> > fork, I've added some unit tests, made it work for Python3 and added 
> > GripsOpen and GripsClose (as synonyms for OpenGrips and CloseGrips) for 
> > consistency with the other verb names. 
> > 
> > Merge in if you like it, otherwise, feel free to bounce it. 
> > 
> > Cheers, 
> > 
> > Eoin. 
> > ------------------------------ 
> > You can merge this Pull Request by running 
> > 
> > git pull https://github.com/eoinwoods/robot_arm master 
> > 
> > Or view, comment on, or merge it at: 
> > 
> > https://github.com/dannystaple/robot_arm/pull/1 
> > Commit Summary 
> > 
> > - Added basic unit test and supporting code in usb_arm.py 
> > - Rename OpenGrips and CloseGrips to GripsOpen and GripsClose for 
> > consistency 
> > - Correction to use unitest.TestCase.assert methods 
> > - Additional tests for command sequences 
> > - Restored CloseGrips and OpenGrips actions to avoid breaking API 
> > - Restored CloseGrips and OpenGrips actions to avoid breaking API 
> > - Added debug print statement for ctrl_transfer() 
> > - Minor key_ctrl.py changes for Python3 
> > - Remove old LED light function 
> > - Update README to note Python 3 compatibility and Grips* action names 
> > 
> > File Changes 
> > 
> > - *M* key_ctrl.py 
> > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-0> (6) 
> > - *M* readme.md 
> > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-1> (10) 
> > - *M* usb_arm.py 
> > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-2> (43) 
> > - *A* usb_arm_test.py 
> > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-3> (104) 
> > 
> > Patch Links: 
> > 
> > - https://github.com/dannystaple/robot_arm/pull/1.patch 
> > - https://github.com/dannystaple/robot_arm/pull/1.diff 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/dannystaple/robot_arm/pull/1>. 
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/dannystaple/robot_arm/pull/1#issuecomment-68988626>.
> 

--
Eoin Woods, Hemel Hempstead, Herfordshire, UK
eoin@copse.org.uk
eoinwoods@gmail.com

**Comment by dannystaple** [comment]
I added myself into the glitter thing - but on my laptop at home (not sure
it'll work at my workplace). The other kit is the uArm - from these guys
https://www.kickstarter.com/projects/ufactory/uarm-put-a-miniature-industrial-robot-arm-on-your.
I think mearm -
http://www.phenoptix.com/products/mearm-pocket-sized-robot-arm are making a
small, cheaper arm - but without the full feedback. It is servo based
though - so easier to position.

**Comment by dannystaple** [comment]
You can then swap out for these servo's -
http://makersify.com/collections/robotics-cnc/products/adafruit-analog-feedback-micro-servo-metal-gear

**Comment by eoinwoods** [comment]
Thanks I will take a look at those.

Eoin.

> On 8 Jan 2015, at 18:30, Danny Staple <notifications@github.com> wrote:
> 
> You can then swap out for these servo's - 
> http://makersify.com/collections/robotics-cnc/products/adafruit-analog-feedback-micro-servo-metal-gear 
> 
> 
> On Thu Jan 08 2015 at 17:56:48 danny staple <danny@orionrobots.co.uk> wrote: 
> 
> > I added myself into the glitter thing - but on my laptop at home (not sure 
> > it'll work at my workplace). The other kit is the uArm - from these guys 
> > https://www.kickstarter.com/projects/ufactory/uarm-put-a-miniature-industrial-robot-arm-on-your. 
> > I think mearm - 
> > http://www.phenoptix.com/products/mearm-pocket-sized-robot-arm are making 
> > a small, cheaper arm - but without the full feedback. It is servo based 
> > though - so easier to position. 
> > 
> > On Wed Jan 07 2015 at 22:22:35 Eoin Woods <notifications@github.com> 
> > wrote: 
> > 
> >> Brilliant, thanks. I have a few other ideas for bits and pieces with it, 
> >> so I’ll send pull requests when I get around to those. 
> >> 
> >> An arm with position feedback would be cool - which kit is that? I’d be 
> >> interested in getting it. 
> >> 
> >> Oh, BTW, just for laughs I added you to the Gitter feed for my fork. 
> >> Gitter is persistent chat for Github - it’s quite nice when you’re 
> >> cooperating on something. Just added you in case you’re interested in 
> >> trying it. 
> >> 
> >> Cheers, 
> >> 
> >> E. 
> >> 
> >> > On 7 Jan 2015, at 07:44, Danny Staple <notifications@github.com> 
> >> wrote: 
> >> > 
> >> > Awesome. I will merge it. I am thinking of writing a compatible api for 
> >> the 
> >> > u factory u arm, with a shim on the arduino - not worked out the detail 
> >> yet 
> >> > as the u arm has servos, and position feedback. 
> >> > 
> >> > On Tue, 6 Jan 2015 21:32 Eoin Woods <notifications@github.com> wrote: 
> >> > 
> >> > > Hi Danny, 
> >> > > 
> >> > > Thanks for writing this really cool module. I've enjoyed using it. On 
> >> my 
> >> > > fork, I've added some unit tests, made it work for Python3 and added 
> >> > > GripsOpen and GripsClose (as synonyms for OpenGrips and CloseGrips) 
> >> for 
> >> > > consistency with the other verb names. 
> >> > > 
> >> > > Merge in if you like it, otherwise, feel free to bounce it. 
> >> > > 
> >> > > Cheers, 
> >> > > 
> >> > > Eoin. 
> >> > > ------------------------------ 
> >> > > You can merge this Pull Request by running 
> >> > > 
> >> > > git pull https://github.com/eoinwoods/robot_arm master 
> >> > > 
> >> > > Or view, comment on, or merge it at: 
> >> > > 
> >> > > https://github.com/dannystaple/robot_arm/pull/1 
> >> > > Commit Summary 
> >> > > 
> >> > > - Added basic unit test and supporting code in usb_arm.py 
> >> > > - Rename OpenGrips and CloseGrips to GripsOpen and GripsClose for 
> >> > > consistency 
> >> > > - Correction to use unitest.TestCase.assert methods 
> >> > > - Additional tests for command sequences 
> >> > > - Restored CloseGrips and OpenGrips actions to avoid breaking API 
> >> > > - Restored CloseGrips and OpenGrips actions to avoid breaking API 
> >> > > - Added debug print statement for ctrl_transfer() 
> >> > > - Minor key_ctrl.py changes for Python3 
> >> > > - Remove old LED light function 
> >> > > - Update README to note Python 3 compatibility and Grips* action 
> >> names 
> >> > > 
> >> > > File Changes 
> >> > > 
> >> > > - *M* key_ctrl.py 
> >> > > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-0> (6) 
> >> > > - *M* readme.md 
> >> > > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-1> (10) 
> >> > > - *M* usb_arm.py 
> >> > > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-2> (43) 
> >> > > - *A* usb_arm_test.py 
> >> > > <https://github.com/dannystaple/robot_arm/pull/1/files#diff-3> (104) 
> >> > > 
> >> > > Patch Links: 
> >> > > 
> >> > > - https://github.com/dannystaple/robot_arm/pull/1.patch 
> >> > > - https://github.com/dannystaple/robot_arm/pull/1.diff 
> >> > > 
> >> > > — 
> >> > > Reply to this email directly or view it on GitHub 
> >> > > <https://github.com/dannystaple/robot_arm/pull/1>. 
> >> > > 
> >> > — 
> >> > Reply to this email directly or view it on GitHub <https://github.com/ 
> >> dannystaple/robot_arm/pull/1#issuecomment-68988626>. 
> >> > 
> >> 
> >> -- 
> >> Eoin Woods, Hemel Hempstead, Herfordshire, UK 
> >> eoin@copse.org.uk 
> >> eoinwoods@gmail.com 
> >> 
> >> — 
> >> Reply to this email directly or view it on GitHub 
> >> <https://github.com/dannystaple/robot_arm/pull/1#issuecomment-69103323>. 
> >> 
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/dannystaple/robot_arm/pull/1#issuecomment-69225151>.
> 

--
Eoin Woods, Hemel Hempstead, Herfordshire, UK
eoin@copse.org.uk
eoinwoods@gmail.com

**Pull request merged**
